[package]
name = "eye"
description = "Cross platform camera capture and control"
version = "0.1.0"
authors = ["Christopher N. Hesse <raymanfx@gmail.com>"]
edition = "2018"
license = "MIT"
readme = "README.md"
repository= "https://github.com/raymanfx/eye-rs"

[features]
default = ["jpeg", "v4l"]
jpeg = ["jpeg-decoder"]

[dependencies]
cfg-if = "0.1"
ffimage = "^0.5"

jpeg-decoder = { version = "^0.1", optional = true }

[target.'cfg(target_os = "linux")'.dependencies.v4l]
version = "^0.7"
optional = true
