[package]
name = "eye"
version = "0.1.0"
authors = ["Christopher N. Hesse <raymanfx@gmail.com>"]
edition = "2018"
license = "MIT"

[features]
default = ["v4l"]

[dependencies]
cfg-if = "0.1"
ffimage = "^0.4"

[target.'cfg(target_os = "linux")'.dependencies.v4l]
version = "^0.5"
optional = true
